In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
veri = pd.read_csv("Student_Performance.csv")
veri

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [12]:
veri.isna().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [13]:
x = veri.drop("Performance Index", axis=1)
y = veri["Performance Index"]

In [14]:
x.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,Yes,9,1
1,4,82,No,4,2
2,8,51,Yes,7,2
3,5,52,Yes,5,2
4,7,75,No,8,5

In [15]:
y.head()

0    91.0
1    65.0
2    45.0
3    36.0
4    66.0
Name: Performance Index, dtype: float64

In [16]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

In [24]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Extracurricular Activities"] 
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_features)],
                                remainder="passthrough"
                                )
transformed_x = transformer.fit_transform(x)

In [26]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(transformed_x, y, test_size=0.2)

In [28]:
model.fit(x_train, y_train);

In [129]:
model.score(x_test, y_test)

0.9846489383526811

In [30]:
y_preds= model.predict(x_test)

In [32]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_true= y_test, y_pred= y_preds)

1.8188021051587302

In [38]:
y_preds[:20]

array([38.57      , 40.19      , 37.86      , 53.02166667, 49.02      ,
       52.03      , 75.31      , 70.28      , 75.11666667, 45.30666667,
       44.662     , 72.64      , 13.41666667, 57.3       , 34.4       ,
       66.13      , 29.58      , 61.87      , 45.51      , 29.90833333])

In [42]:
np.array(y_test[:20])

array([42., 42., 39., 58., 49., 50., 77., 69., 75., 41., 43., 71., 12.,
       54., 36., 67., 31., 57., 46., 29.])